{% set name = "facexlib" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/facexlib-{{ version }}.tar.gz
  sha256: 7ae784a520eb52e05583e8bf9f68f77f45083239ac754d646d635017b49e7763

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - cython
    - numpy
  run:
    - python >=3.6
    - filterpy
    - numba
    - numpy
    - opencv
    - pillow
    - scipy
    - pytorch
    - torchvision
    - tqdm

test:
  imports:
    - facexlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xinntao/facexlib
  summary: Basic face library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
